name: payment-service
version: 0.1.0.0
github: "githubuser/payment-service"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/payment-service#readme>

dependencies:
  - base >= 4.7 && < 5
  - warp >= 3.3.0 && < 4
  - wai >= 3.2.2.1 && < 4
  - http-types >= 0.12.3 && < 0.13

library:
  source-dirs: src

executables:
  payment-service-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - payment-service

tests:
  payment-service-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - payment-service
